Repository PyFilesystem/pyfilesystem2, pull requests merged in 2021-03, with the labels that each got.

#457 In fs.ftpfs.FTPFS.upload, replaced `self._manage_ftp` by `self.ftp`.
  CHANGELOG.md
  fs/ftpfs.py
  tests/test_ftpfs.py
Labels: enhancement

#470 Fix miscellaneous bugs in `fs.wrap`
  CHANGELOG.md
  fs/wrap.py
  tests/test_wrap.py
Labels: bug

#472 Add optimized implementations of several `MemoryFS` methods
  CHANGELOG.md
  fs/memoryfs.py
  fs/test.py
  tests/test_memoryfs.py
Labels: enhancement

#473 Fix FTP not properly parsing lines with sticky/SUID/SGID permissions
  CHANGELOG.md
  fs/_ftp_parse.py
  tests/test_ftp_parse.py
Labels: bug

#474 Add missing `exc` argument to `PathError`
  CHANGELOG.md
  fs/errors.py
  tests/test_error_tools.py
Labels: bug

#475 Fix minor issues in `OSFS.scandir`
  CHANGELOG.md
  fs/osfs.py
  fs/test.py
  tests/test_osfs.py
Labels: bug

#467 Update docs and add doctest loading mechanism
  CHANGELOG.md
  fs/_ftp_parse.py
  fs/_repr.py
  fs/_url_tools.py
  fs/base.py
  fs/filesize.py
  fs/ftpfs.py
  fs/glob.py
  fs/info.py
  fs/opener/registry.py
  fs/path.py
  fs/permissions.py
  fs/tarfs.py
  fs/tempfs.py
  fs/test.py
  fs/time.py
  fs/walk.py
  fs/wrap.py
  fs/wrapfs.py
  fs/zipfs.py
  setup.cfg
  tests/test_doctest.py
Labels: docs, enhancement
